<?php

namespace AlexStack\LaravelCms;

use AlexStack\LaravelCms\Helpers\LaravelCmsHelper;
use Illuminate\Database\Seeder;

class CmsPagesTableSeeder extends Seeder
{
    private $config;
    private $table_name;

    public function __construct()
    {
        $this->config     = include base_path('config/laravel-cms.php');
        $this->table_name = $this->config['table_name']['pages'];
        $this->helper     = new LaravelCmsHelper();
    }

    /**
     * Auto generated seed file.
     */
    public function run()
    {
        \DB::table($this->table_name)->delete();

        \DB::table($this->table_name)->insert([
            0 => [
                'id'               => 5,
                'user_id'          => null,
                'parent_id'        => null,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => 'About Our Team',
                'menu_title'       => $this->helper->t('about,us'),
                'slug'             => 'AboutUs.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>About Us example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => 100,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:23:53',
                'updated_at'       => '2019-08-24 23:56:37',
            ],
            1 => [
                'id'               => 2,
                'user_id'          => null,
                'parent_id'        => null,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('contact,us'),
                'menu_title'       => $this->helper->t('contact,us'),
                'slug'             => 'Contact-Us.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Contact us example page</p><p><br></p><p>Contact us example page<br></p><p><br></p>',
                'sort_value'       => 7000,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:24:33',
                'updated_at'       => '2019-08-25 23:56:52',
            ],
            2 => [
                'id'               => 3,
                'user_id'          => null,
                'parent_id'        => null,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('our,services'),
                'menu_title'       => $this->helper->t('services'),
                'slug'             => 'Our-Services.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Our Services main content example</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => 8000,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:24:50',
                'updated_at'       => '2019-08-23 23:56:45',
            ],
            3 => [
                'id'               => 4,
                'user_id'          => null,
                'parent_id'        => null,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('our,products'),
                'menu_title'       => $this->helper->t('products'),
                'slug'             => '4.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Our Products example page</p><p><br></p><p>Our Products example page</p><p><br></p><p>Our Products example page</p><p><br></p><p><br></p>',
                'sort_value'       => 9000,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:25:33',
                'updated_at'       => '2019-08-22 23:50:52',
            ],
            4 => [
                'id'               => 1,
                'user_id'          => null,
                'parent_id'        => null,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('homepage'),
                'menu_title'       => $this->helper->t('home'),
                'slug'             => 'homepage',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>This is the home page main content. </p><p>You can change it in the cms backend : </p><p>Please keep only one <span style="font-weight: bold;">slug </span>settings in the SEO tab as <span style="color: rgb(156, 0, 255); font-weight: bold;">homepage</span>.</p><p><a href="/cmsadmin/">Click here go to the cms backend,</a> you will need to log in as the first user on the website.</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => 60000,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:25:50',
                'updated_at'       => '2019-09-15 23:47:10',
            ],
            5 => [
                'id'               => 6,
                'user_id'          => null,
                'parent_id'        => 4,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('sub,product').' 1',
                'menu_title'       => null,
                'slug'             => '6.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Sub Product 1 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => null,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:52:00',
                'updated_at'       => '2019-08-15 23:57:20',
            ],
            6 => [
                'id'               => 7,
                'user_id'          => null,
                'parent_id'        => 4,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('sub,product').' 2',
                'menu_title'       => null,
                'slug'             => '7.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Sub Product 2 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => null,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:52:47',
                'updated_at'       => '2019-08-15 23:57:13',
            ],
            7 => [
                'id'               => 8,
                'user_id'          => null,
                'parent_id'        => 4,
                'menu_enabled'     => 1,
                'status'           => 'publish',
                'title'            => $this->helper->t('sub,product').' 3',
                'menu_title'       => null,
                'slug'             => '8.html',
                'template_file'    => null,
                'meta_title'       => null,
                'meta_keywords'    => null,
                'meta_description' => null,
                'abstract'         => null,
                'main_banner'      => null,
                'main_image'       => null,
                'sub_content'      => null,
                'main_content'     => '<p>Sub Product 3 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value'       => null,
                'view_counts'      => null,
                'tags'             => null,
                'extra_image_2'    => null,
                'extra_text_2'     => null,
                'extra_content_2'  => null,
                'file_data'        => '[]',
                'redirect_url'     => null,
                'deleted_at'       => null,
                'created_at'       => '2019-08-15 23:53:42',
                'updated_at'       => '2019-08-15 23:57:04',
            ],
        ]);
    }
}
