<?php

namespace AlexStack\LaravelCms;

use Illuminate\Database\Seeder;

class CmsPagesTableSeeder extends Seeder
{
    private $config;
    private $table_name;
    public function __construct()
    {
        $this->config = include(base_path('config/laravel-cms.php'));
        $this->table_name = $this->config['table_name']['pages'];
    }
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table($this->table_name)->delete();

        \DB::table($this->table_name)->insert(array(
            0 =>
            array(
                'id' => 5,
                'user_id' => NULL,
                'parent_id' => NULL,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'About Our Team',
                'menu_title' => 'About Us',
                'slug' => 'AboutUs.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>About Us example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:23:53',
                'updated_at' => '2019-08-15 23:56:37',
            ),
            1 =>
            array(
                'id' => 2,
                'user_id' => NULL,
                'parent_id' => NULL,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Contact Us',
                'menu_title' => 'Contact',
                'slug' => 'Contact-Us.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Contact us example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:24:33',
                'updated_at' => '2019-08-15 23:56:52',
            ),
            2 =>
            array(
                'id' => 3,
                'user_id' => NULL,
                'parent_id' => NULL,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Our Services',
                'menu_title' => 'Services',
                'slug' => 'Our-Services.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Our Services main content example</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:24:50',
                'updated_at' => '2019-08-15 23:56:45',
            ),
            3 =>
            array(
                'id' => 4,
                'user_id' => NULL,
                'parent_id' => NULL,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Our Products',
                'menu_title' => 'Products',
                'slug' => '4.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Our Products example page</p><p><br></p><p>Our Products example page</p><p><br></p><p>Our Products example page</p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:25:33',
                'updated_at' => '2019-08-15 23:50:52',
            ),
            4 =>
            array(
                'id' => 1,
                'user_id' => NULL,
                'parent_id' => NULL,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Homepage',
                'menu_title' => 'Home',
                'slug' => 'homepage',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>This is the home page main content. </p><p>You can change it in the cms backend : </p><p>Please keep only one <span style="font-weight: bold;">slug </span>settings in the SEO tab as <span style="color: rgb(156, 0, 255); font-weight: bold;">homepage</span>.</p><p><a href="/cmsadmin/">Click here go to the cms backend,</a> you will need to log in as the first user on the website.</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:25:50',
                'updated_at' => '2019-08-15 23:47:10',
            ),
            5 =>
            array(
                'id' => 6,
                'user_id' => NULL,
                'parent_id' => 4,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Sub Product 1',
                'menu_title' => 'Product 1',
                'slug' => '6.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Sub Product 1 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:52:00',
                'updated_at' => '2019-08-15 23:57:20',
            ),
            6 =>
            array(
                'id' => 7,
                'user_id' => NULL,
                'parent_id' => 4,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Sub Product 2',
                'menu_title' => 'Product 2',
                'slug' => '7.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Sub Product 2 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:52:47',
                'updated_at' => '2019-08-15 23:57:13',
            ),
            7 =>
            array(
                'id' => 8,
                'user_id' => NULL,
                'parent_id' => 4,
                'menu_enabled' => 1,
                'status' => 'publish',
                'title' => 'Sub Product 3',
                'menu_title' => 'Product 3',
                'slug' => '8.html',
                'template_file' => NULL,
                'meta_title' => NULL,
                'meta_keywords' => NULL,
                'meta_description' => NULL,
                'abstract' => NULL,
                'main_banner' => NULL,
                'main_image' => NULL,
                'sub_content' => NULL,
                'main_content' => '<p>Sub Product 3 example page</p><p><br></p><p><br></p><p><br></p>',
                'sort_value' => NULL,
                'view_counts' => NULL,
                'tags' => NULL,
                'extra_image_2' => NULL,
                'extra_text_2' => NULL,
                'extra_content_2' => NULL,
                'file_data' => '[]',
                'redirect_url' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2019-08-15 23:53:42',
                'updated_at' => '2019-08-15 23:57:04',
            ),
        ));
    }
}
